title: Setup Your IJ.Start.Canon Printer 
description: Visit ij.start.canon to setup your ij canon printer and follow the steps to download and install the canon printer driver.
theme: jekyll-theme-minimal
